# Generated by Django 5.1.3 on 2024-12-03 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HostelApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlord",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="room",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="HostelApp.student",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_photo",
            field=models.ImageField(blank=True, null=True, upload_to="room_photos/"),
        ),
    ]
